language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install --no-scripts --no-suggest --no-interaction

script:
  - vendor/bin/phpunit